In [2]:
import pandas as pd
import numpy as np

In [3]:
cleaned_test_df=pd.read_csv("/Users/amelchristy/Downloads/Amazon_R/cleaned_test.csv")

In [4]:
encoded_cleaned_test_df=pd.read_csv("/Users/amelchristy/Downloads/Amazon_R/encoded_cleaned_test.csv")

In [5]:
# Create a new DataFrame to hold the combined unique mappings for all specified columns
all_combined_unique_df = pd.DataFrame()

# Loop over each column to create unique mappings and add them to the DataFrame
for col in ['Weather', 'Road_traffic_density', 'Vehicle_condition', 'Type_of_order', 'Type_of_vehicle','City']:
    # Combine the encoded and cleaned columns into a single column in the format "encoded:cleaned"
    combined_col = encoded_cleaned_test_df[col].astype(str) + ':' + cleaned_test_df[col].astype(str)
    # Get unique combinations and create a DataFrame
    unique_col_df = pd.DataFrame({col + '_combined': combined_col.unique()})
    # Concatenate to the main DataFrame
    all_combined_unique_df = pd.concat([all_combined_unique_df, unique_col_df], axis=1)

# Display the DataFrame with all unique mappings
all_combined_unique_df

,Weather_combined,Road_traffic_density_combined,Vehicle_condition_combined,Type_of_order_combined,Type_of_vehicle_combined,City_combined
0,7:nan,4:nan,3:3,1:Drinks,1:electric_scooter,0:Metropolitian
1,6:Windy,1:Jam,0:0,3:Snack,2:motorcycle,2:Urban
2,3:Stormy,3:Medium,1:1,2:Meal,3:scooter,3:nan
3,1:Fog,2:Low,2:2,0:Buffet,bicycle:bicycle,Semi-2:Semi-Urban
4,4:Sunny,0:High,NaN,NaN,NaN,NaN
5,0:Cloudy,NaN,NaN,NaN,NaN,NaN
6,2:Sandstorms,NaN,NaN,NaN,NaN,NaN

In [11]:
amazon =pd.read_csv("/Users/amelchristy/Downloads/Amazon_R/updated.csv")

In [13]:
# Define the mappings based on your provided combined unique values
# Ensure the keys are integers if the original dataframe has integers
weather_mapping = {7: None, 6: 'Windy', 3: 'Stormy', 1: 'Fog', 4: 'Sunny', 0: 'Cloudy', 2: 'Sandstorms'}
traffic_mapping = {4: None, 1: 'Jam', 3: 'Medium', 2: 'Low', 0: 'High'}
vehicle_condition_mapping = {3: 'Poor', 0: 'Excellent', 1: 'Good', 2: 'Fair'}
type_of_order_mapping = {1: 'Drinks', 3: 'Snack', 2: 'Meal', 0: 'Buffet'}
type_of_vehicle_mapping = {1: 'Electric Scooter', 2: 'Motorcycle', 3: 'Scooter', 4: 'Bicycle'}
city_mapping = {0: 'Metropolitian', 1: 'Urban', 2: 'Semi-Urban'}



# Apply the mappings to the 'amazon' dataframe
amazon['Weatherconditions'] = amazon['Weatherconditions'].map(weather_mapping).fillna(amazon['Weatherconditions'])
amazon['Road_traffic_density'] = amazon['Road_traffic_density'].map(traffic_mapping).fillna(amazon['Road_traffic_density'])
amazon['Vehicle_condition'] = amazon['Vehicle_condition'].map(vehicle_condition_mapping).fillna(amazon['Vehicle_condition'])
amazon['Type_of_order'] = amazon['Type_of_order'].map(type_of_order_mapping).fillna(amazon['Type_of_order'])
amazon['Type_of_vehicle'] = amazon['Type_of_vehicle'].map(type_of_vehicle_mapping).fillna(amazon['Type_of_vehicle'])
amazon['City'] = amazon['City'].map(city_mapping).fillna(amazon['City'])

amazon.head()

,Unnamed: 0,ID,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Time_Orderd,Time_Order_picked,Weatherconditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken(min)
0,1,0x4607_x,INDORES13DEL02,37,4.9,22.745049,75.892471,22.765049,75.912471,11:30,11:45,Sunny,High,Fair,Snack,Scooter,0.0,1,3,24.0
1,2,0xb379_x,BANGRES18DEL02,34,4.5,12.913041,77.683237,13.043041,77.813237,19:45,19:50,Stormy,Jam,Fair,Snack,Bicycle,1.0,1,Urban,33.0
2,3,0x20f7_x,BANGRES18DEL01,37,4.4,12.913041,77.683237,12.953041,77.723237,13:50,13:55,Windy,High,Excellent,Buffet,Scooter,2.0,1,Urban,42.0
3,4,0x7804_x,HYDRES13DEL02,28,4.9,17.431477,78.400350,17.451477,78.420350,10:60,11:15,Sandstorms,Low,Good,Meal,Bicycle,1.0,1,3,19.0
4,5,0x7faf_x,RANCHIRES07DEL01,37,4.6,23.359407,85.325055,23.429407,85.395055,23:50,23:60,Stormy,Low,Excellent,Meal,Scooter,1.0,1,Urban,25.0

In [ ]:
amazon.to_csv('.../amazon_updated.csv', index=False)